[install]
# Configure Bun package manager behavior
cache = true
exact = false

[run]
# Environment variables for running scripts
env = { PRINTERS_JS_SIMULATE = "true" }

# JSR registry support
[install.registry]
jsr = "https://jsr.io/"