[package]
name = "deno-printers"
authors = ["Evan Simkowitz <esimkowitz@users.noreply.github.com>"]
version = "0.1.3"
edition = "2021"
publish = false

[dependencies]
lazy_static = "1.5.0"
printers = "2.2.0"
serde_json = "1.0.143"

[lib]
crate-type = ["cdylib"]
