name: Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.2.3

jobs:
  build-native:
    name: Build native libraries
    runs-on: ${{ matrix.os }}
    permissions: {}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-amd64.so
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-arm64.so
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-amd64.dll
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-arm64.dll
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: libprinters_js.dylib
            release_name: libprinters_js-macos-arm64.dylib

    steps:
      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install system dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install cross for ARM64 cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross

      - name: Build native library
        shell: bash
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Prepare artifact for target/release structure
        shell: bash
        run: |
          mkdir -p target/release
          # Map target to expected filename in target/release/
          case "${{ matrix.target }}" in
            "x86_64-unknown-linux-gnu")
              cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} target/release/libprinters_js.so
              ;;
            "aarch64-unknown-linux-gnu")
              cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} target/release/libprinters_js-arm64.so
              ;;
            "x86_64-pc-windows-msvc")
              cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} target/release/printers_js.dll
              ;;
            "aarch64-pc-windows-msvc")
              cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} target/release/printers_js-arm64.dll
              ;;
            "aarch64-apple-darwin")
              cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} target/release/libprinters_js.dylib
              ;;
          esac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target-release-${{ matrix.target }}
          path: |
            target/release/*.so
            target/release/*.dll
            target/release/*.dylib
          if-no-files-found: error

  build-napi:
    name: Build N-API modules
    runs-on: ${{ matrix.settings.host }}
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        settings:
          # macOS builds
          - host: macos-13 # Intel Mac
            target: x86_64-apple-darwin

          - host: macos-14 # Apple Silicon
            target: aarch64-apple-darwin

          # Windows builds
          - host: windows-latest
            target: x86_64-pc-windows-msvc

          # Windows ARM64 - use native ARM64 runner
          - host: windows-11-arm
            target: aarch64-pc-windows-msvc

          # Linux builds
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # Linux ARM64 - use native ARM64 runner
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    steps:
      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      # Install Task runner for building
      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Our build script auto-detects the platform and builds for the current target
          echo "Building for target: ${{ matrix.settings.target }}"
          task build:napi

      - name: Prepare N-API artifacts for npm/ structure
        shell: bash
        run: |
          # Map NAPI-RS platform names to npm directory names
          case "${{ matrix.settings.target }}" in
            "x86_64-apple-darwin") npm_platform="darwin-x64" ;;
            "aarch64-apple-darwin") npm_platform="darwin-arm64" ;;
            "x86_64-pc-windows-msvc") npm_platform="win32-x64-msvc" ;;
            "aarch64-pc-windows-msvc") npm_platform="win32-arm64-msvc" ;;
            "x86_64-unknown-linux-gnu") npm_platform="linux-x64-gnu" ;;
            "aarch64-unknown-linux-gnu") npm_platform="linux-arm64-gnu" ;;
            *) echo "Unknown platform: ${{ matrix.settings.target }}"; exit 1 ;;
          esac

          echo "Mapping ${{ matrix.settings.target }} to npm/$npm_platform"

          # Create npm platform directory structure
          mkdir -p "npm/$npm_platform"

          # Find and copy .node files to the correct platform directory
          find . -name "*.node" -type f -exec cp {} "npm/$npm_platform/" \;

          # Copy JS/TS files to platform directory (if they exist)
          find npm -name "index.js" -type f -exec cp {} "npm/$npm_platform/" \; 2>/dev/null || true
          find npm -name "index.d.ts" -type f -exec cp {} "npm/$npm_platform/" \; 2>/dev/null || true

          echo "Contents of npm/$npm_platform:"
          ls -la "npm/$npm_platform/"

      - name: Upload N-API artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-binaries-${{ matrix.settings.target }}
          path: npm/
          if-no-files-found: error

  test-targets:
    name: Cross-runtime test on ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    needs: [build-napi, build-native]
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        # We can't run the cross-runtime tests on Windows ARM runners because Deno and Bun do not have ARM64 Windows builds
        settings:
          # macOS builds
          - host: macos-13 # Intel Mac
            target: x86_64-apple-darwin

          - host: macos-14 # Apple Silicon
            target: aarch64-apple-darwin

          # Windows builds
          - host: windows-latest
            target: x86_64-pc-windows-msvc

          # Linux builds
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # Linux ARM64 - use native ARM64 runner
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
    steps:
      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          no-cache: true

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      # Install Task runner
      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: .
          merge-multiple: true

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run comprehensive tests
        run: task test

  publish:
    name: Publish to ${{ matrix.registry }}
    runs-on: ubuntu-latest
    needs: test-targets
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        include:
          - registry: jsr
            publish_command: "deno publish --allow-dirty --no-check"
            env_vars: {}
          - registry: npm
            publish_command: "npm publish --access public"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Deno
        if: matrix.registry == 'jsr'
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: false

      - name: Setup Node
        if: matrix.registry == 'npm'
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: .
          merge-multiple: true

      - name: Publish to ${{ matrix.registry }}
        run: ${{ matrix.publish_command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
