name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-cross-runtime:
    name: Test all runtimes
    runs-on: ubuntu-latest
    env:
      PRINTERS_JS_SIMULATE: true # Force simulation mode for all tests
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      # Cache Rust dependencies for faster builds
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build all runtimes
        run: deno task build:all

      - name: Run comprehensive tests
        run: deno task test:all

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/

  build-native:
    name: Build native libraries
    runs-on: ${{ matrix.os }}
    needs: test-cross-runtime
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-amd64.so
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-arm64.so
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-amd64.dll
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-arm64.dll
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: libprinters_js.dylib
            release_name: libprinters_js-macos-arm64.dylib

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install system dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install cross for ARM64 cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Build native library
        shell: bash
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.release_name }}

      - name: Generate checksum
        shell: bash
        run: |
          cd artifacts
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum ${{ matrix.release_name }} > ${{ matrix.release_name }}.sha256
          else
            shasum -a 256 ${{ matrix.release_name }} > ${{ matrix.release_name }}.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: artifacts/*

  build-napi:
    name: Build N-API modules
    runs-on: ${{ matrix.settings.host }}
    needs: test-cross-runtime
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin

          - host: macos-latest
            target: aarch64-apple-darwin

          - host: windows-latest
            target: x86_64-pc-windows-msvc

          - host: windows-latest
            target: aarch64-pc-windows-msvc

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v5

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang gcc-aarch64-linux-gnu

      - name: Setup cross-compilation for ARM64
        if: matrix.settings.target == 'aarch64-unknown-linux-gnu'
        run: |
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --target ${{ matrix.settings.target }}

      - name: Debug build output
        shell: bash
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of napi/ directory (if it exists):"
          ls -la napi/ || echo "napi/ directory does not exist"
          echo "Looking for .node files:"
          find . -name "*.node" -type f || echo "No .node files found"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: napi/*.node
          if-no-files-found: error

  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: [build-native, build-napi]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Organize binaries
        run: |
          mkdir -p napi
          mkdir -p target/release

          # Copy N-API binaries for Node.js
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              cp "$dir"/*.node napi/ 2>/dev/null || true
            fi
          done

          # Copy FFI binaries for potential Deno/Bun usage from Node package
          cp artifacts/x86_64-unknown-linux-gnu/libprinters_js-linux-amd64.so target/release/libprinters_js.so 2>/dev/null || true
          cp artifacts/aarch64-unknown-linux-gnu/libprinters_js-linux-arm64.so target/release/libprinters_js-arm64.so 2>/dev/null || true
          cp artifacts/x86_64-pc-windows-msvc/printers_js-windows-amd64.dll target/release/printers_js.dll 2>/dev/null || true
          cp artifacts/aarch64-pc-windows-msvc/printers_js-windows-arm64.dll target/release/printers_js-arm64.dll 2>/dev/null || true
          cp artifacts/aarch64-apple-darwin/libprinters_js-macos-arm64.dylib target/release/libprinters_js.dylib 2>/dev/null || true

          echo "N-API binaries:"
          ls -la napi/
          echo "FFI binaries:"
          ls -la target/release/ || echo "No FFI binaries included"

      - name: Publish to JSR
        run: deno publish --allow-dirty --no-check

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [build-native, build-napi]
    env:
      PRINTERS_JS_SIMULATE: true # Force simulation mode for tests
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Organize all binaries
        run: |
          mkdir -p napi
          mkdir -p target/release

          # Copy N-API binaries for Node.js
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              cp "$dir"/*.node napi/ 2>/dev/null || true
            fi
          done

          # Copy FFI binaries for potential Deno/Bun usage from Node package
          cp artifacts/x86_64-unknown-linux-gnu/libprinters_js-linux-amd64.so target/release/libprinters_js.so 2>/dev/null || true
          cp artifacts/aarch64-unknown-linux-gnu/libprinters_js-linux-arm64.so target/release/libprinters_js-arm64.so 2>/dev/null || true
          cp artifacts/x86_64-pc-windows-msvc/printers_js-windows-amd64.dll target/release/printers_js.dll 2>/dev/null || true
          cp artifacts/aarch64-pc-windows-msvc/printers_js-windows-arm64.dll target/release/printers_js-arm64.dll 2>/dev/null || true
          cp artifacts/aarch64-apple-darwin/libprinters_js-macos-arm64.dylib target/release/libprinters_js.dylib 2>/dev/null || true

          echo "N-API binaries:"
          ls -la napi/
          echo "FFI binaries:"
          ls -la target/release/ || echo "No FFI binaries included"

      - name: Test Node.js package before publishing
        run: PRINTERS_JS_SIMULATE=true npm test

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
