name: Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.2.3

jobs:
  test-cross-runtime:
    name: Test all runtimes
    runs-on: ubuntu-latest
    env:
      PRINTERS_JS_SIMULATE: true # Force simulation mode for all tests
      CARGO_TERM_COLOR: always
    permissions: {}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          no-cache: true

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build all runtimes
        run: deno task build:all

      - name: Run comprehensive tests
        run: deno task test:all

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/

  build-native:
    name: Build native libraries
    runs-on: ${{ matrix.os }}
    needs: test-cross-runtime
    permissions: {}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-amd64.so
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: libprinters_js.so
            release_name: libprinters_js-linux-arm64.so
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-amd64.dll
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            artifact_name: printers_js.dll
            release_name: printers_js-windows-arm64.dll
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: libprinters_js.dylib
            release_name: libprinters_js-macos-arm64.dylib

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install system dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install cross for ARM64 cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross

      - name: Build native library
        shell: bash
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.release_name }}

      - name: Generate checksum
        shell: bash
        run: |
          cd artifacts
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum ${{ matrix.release_name }} > ${{ matrix.release_name }}.sha256
          else
            shasum -a 256 ${{ matrix.release_name }} > ${{ matrix.release_name }}.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: artifacts/*

  build-napi:
    name: Build N-API modules
    runs-on: ${{ matrix.settings.host }}
    needs: test-cross-runtime
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        settings:
          # macOS builds
          - host: macos-13 # Intel Mac
            target: x86_64-apple-darwin

          - host: macos-14 # Apple Silicon
            target: aarch64-apple-darwin

          # Windows builds
          - host: windows-latest
            target: x86_64-pc-windows-msvc

          # Windows ARM64 - use native ARM64 runner
          - host: windows-11-arm
            target: aarch64-pc-windows-msvc

          # Linux builds
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # Linux ARM64 - use native ARM64 runner
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v5

      # Speed up apt-get operations by disabling unnecessary man-db auto-update
      - name: Disable man-db auto-update
        if: runner.os == 'Linux'
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo rm -f /var/lib/man-db/auto-update

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev pkg-config clang

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Our build script auto-detects the platform and builds for the current target
          echo "Building for target: ${{ matrix.settings.target }}"
          npm run build

      - name: Debug build output
        shell: bash
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of npm/ directory (if it exists):"
          ls -la npm/ || echo "npm/ directory does not exist"
          echo "Platform-specific directories:"
          ls -la npm/*/ 2>/dev/null || echo "No platform directories found"
          echo "Looking for .node files:"
          find . -name "*.node" -type f || echo "No .node files found"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: npm/**/*.node
          if-no-files-found: error

      # Upload index.js and index.d.ts only once (from the first job that completes)
      - name: Upload N-API JavaScript files
        if: matrix.settings.target == 'x86_64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: napi-js-files
          path: |
            npm/*/index.js
            npm/*/index.d.ts
          if-no-files-found: error

  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: [build-native, build-napi]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: false

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Setup binaries for JSR
        run: |
          mkdir -p target/release

          # Copy FFI binaries for Deno/Bun
          cp artifacts/x86_64-unknown-linux-gnu/libprinters_js-linux-amd64.so target/release/libprinters_js.so
          cp artifacts/aarch64-unknown-linux-gnu/libprinters_js-linux-arm64.so target/release/libprinters_js-arm64.so
          cp artifacts/x86_64-pc-windows-msvc/printers_js-windows-amd64.dll target/release/printers_js.dll
          cp artifacts/aarch64-pc-windows-msvc/printers_js-windows-arm64.dll target/release/printers_js-arm64.dll
          cp artifacts/aarch64-apple-darwin/libprinters_js-macos-arm64.dylib target/release/libprinters_js.dylib

          # Create npm directory structure and copy N-API binaries directly to platform dirs
          npx napi create-npm-dirs

          # Copy N-API binaries to correct platform directories
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir" | sed 's/bindings-//')
              # Map NAPI-RS platform names to npm directory names
              case "$platform" in
                "x86_64-apple-darwin") npm_platform="darwin-x64" ;;
                "aarch64-apple-darwin") npm_platform="darwin-arm64" ;;
                "x86_64-pc-windows-msvc") npm_platform="win32-x64-msvc" ;;
                "aarch64-pc-windows-msvc") npm_platform="win32-arm64-msvc" ;;
                "x86_64-unknown-linux-gnu") npm_platform="linux-x64-gnu" ;;
                "aarch64-unknown-linux-gnu") npm_platform="linux-arm64-gnu" ;;
                *) echo "Unknown platform: $platform"; continue ;;
              esac

              if [ -d "npm/$npm_platform" ]; then
                find "$dir" -name "*.node" -exec cp {} "npm/$npm_platform/" \; 2>/dev/null || true
                echo "Copied .node files to npm/$npm_platform/"
              fi
            fi
          done

          # Copy N-API JavaScript files to each platform directory
          if [ -d "artifacts/napi-js-files" ]; then
            for platform_dir in npm/*/; do
              if [ -d "$platform_dir" ]; then
                cp artifacts/napi-js-files/*.js "$platform_dir/" 2>/dev/null || true
                cp artifacts/napi-js-files/*.d.ts "$platform_dir/" 2>/dev/null || true
                echo "Copied JS/TS files to $platform_dir"
              fi
            done
          fi

          echo "FFI binaries:"
          ls -la target/release/
          echo "N-API platform directories:"
          ls -la npm/*/

      - name: Publish to JSR
        run: deno publish --allow-dirty --no-check

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [build-native, build-napi]
    env:
      PRINTERS_JS_SIMULATE: true # Force simulation mode for tests
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Organize all binaries
        run: |
          mkdir -p target/release

          # Copy FFI binaries for Deno/Bun
          cp artifacts/x86_64-unknown-linux-gnu/libprinters_js-linux-amd64.so target/release/libprinters_js.so
          cp artifacts/aarch64-unknown-linux-gnu/libprinters_js-linux-arm64.so target/release/libprinters_js-arm64.so
          cp artifacts/x86_64-pc-windows-msvc/printers_js-windows-amd64.dll target/release/printers_js.dll
          cp artifacts/aarch64-pc-windows-msvc/printers_js-windows-arm64.dll target/release/printers_js-arm64.dll
          cp artifacts/aarch64-apple-darwin/libprinters_js-macos-arm64.dylib target/release/libprinters_js.dylib

          # Create npm directory structure and copy N-API binaries directly to platform dirs
          npx napi create-npm-dirs

          # Copy N-API binaries to correct platform directories
          for dir in artifacts/bindings-*; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir" | sed 's/bindings-//')
              # Map NAPI-RS platform names to npm directory names
              case "$platform" in
                "x86_64-apple-darwin") npm_platform="darwin-x64" ;;
                "aarch64-apple-darwin") npm_platform="darwin-arm64" ;;
                "x86_64-pc-windows-msvc") npm_platform="win32-x64-msvc" ;;
                "aarch64-pc-windows-msvc") npm_platform="win32-arm64-msvc" ;;
                "x86_64-unknown-linux-gnu") npm_platform="linux-x64-gnu" ;;
                "aarch64-unknown-linux-gnu") npm_platform="linux-arm64-gnu" ;;
                *) echo "Unknown platform: $platform"; continue ;;
              esac

              if [ -d "npm/$npm_platform" ]; then
                find "$dir" -name "*.node" -exec cp {} "npm/$npm_platform/" \; 2>/dev/null || true
                echo "Copied .node files to npm/$npm_platform/"
              fi
            fi
          done

          # Copy N-API JavaScript files to each platform directory
          if [ -d "artifacts/napi-js-files" ]; then
            for platform_dir in npm/*/; do
              if [ -d "$platform_dir" ]; then
                cp artifacts/napi-js-files/*.js "$platform_dir/" 2>/dev/null || true
                cp artifacts/napi-js-files/*.d.ts "$platform_dir/" 2>/dev/null || true
                echo "Copied JS/TS files to $platform_dir"
              fi
            done
          fi

          echo "FFI binaries:"
          ls -la target/release/
          echo "N-API platform directories:"
          ls -la npm/*/

      - name: Test Node.js package before publishing
        run: PRINTERS_JS_SIMULATE=true npm test

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
